set_property PACKAGE_PIN B1 [get_ports sclk]
set_property IOSTANDARD LVCMOS33 [get_ports sclk]
set_property PACKAGE_PIN C2 [get_ports miso]
set_property IOSTANDARD LVCMOS33 [get_ports miso]
set_property PACKAGE_PIN C1 [get_ports mosi]
set_property IOSTANDARD LVCMOS33 [get_ports mosi]
set_property PACKAGE_PIN D2 [get_ports cs]
set_property IOSTANDARD LVCMOS33 [get_ports cs]

set_property PACKAGE_PIN J15 [get_ports {sd_error_code[0]}]
set_property PACKAGE_PIN L16 [get_ports {sd_error_code[1]}]
set_property PACKAGE_PIN M13 [get_ports {sd_error_code[2]}]
set_property PACKAGE_PIN R15 [get_ports {sd_error_code[3]}]
set_property PACKAGE_PIN R17 [get_ports {sd_error_code[4]}]
set_property PACKAGE_PIN T18 [get_ports {sd_error_code[5]}]
set_property PACKAGE_PIN U18 [get_ports {sd_error_code[6]}]
set_property PACKAGE_PIN R13 [get_ports {sd_error_code[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sd_error_code[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sd_error_code[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sd_error_code[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sd_error_code[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sd_error_code[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sd_error_code[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sd_error_code[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sd_error_code[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports sd_busy]
set_property IOSTANDARD LVCMOS33 [get_ports sd_error]
set_property IOSTANDARD LVCMOS33 [get_ports sd_read_done]
set_property PACKAGE_PIN G14 [get_ports sd_busy]
set_property PACKAGE_PIN N15 [get_ports sd_error]
set_property PACKAGE_PIN R11 [get_ports sd_read_done]


set_property PACKAGE_PIN E2 [get_ports sd_reset]
set_property IOSTANDARD LVCMOS33 [get_ports sd_reset]
set_property PACKAGE_PIN A1 [get_ports cd]
set_property IOSTANDARD LVCMOS33 [get_ports cd]
